"""Add phone to Student

Revision ID: 0627c3cfac47
Revises: 58706c638341
Create Date: 2025-05-26 00:46:50.772247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0627c3cfac47'
down_revision = '58706c638341'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.alter_column('gender',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               nullable=False)
        batch_op.alter_column('registration_number',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('student_number',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('program',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('year_of_intake',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=10),
               nullable=False)
        batch_op.drop_constraint('student_email_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.create_unique_constraint('student_email_key', ['email'])
        batch_op.alter_column('year_of_intake',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('program',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('student_number',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('registration_number',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('gender',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.drop_column('phone')

    # ### end Alembic commands ###
