"""Add phone and gender to Supervisor

Revision ID: 1cfb37944cf3
Revises: 57895a4eb094
Create Date: 2025-05-14 19:30:15.818277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cfb37944cf3'
down_revision = '57895a4eb094'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supervisor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('gender', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supervisor', schema=None) as batch_op:
        batch_op.drop_column('gender')
        batch_op.drop_column('phone')

    # ### end Alembic commands ###
