"""empty message

Revision ID: 57895a4eb094
Revises: 083e7aa9ac95
Create Date: 2025-05-14 11:29:42.864078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57895a4eb094'
down_revision = '083e7aa9ac95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_supervisors', schema=None) as batch_op:
        batch_op.alter_column('student_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('supervisor_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_supervisors', schema=None) as batch_op:
        batch_op.alter_column('supervisor_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('student_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
