"""Initial clean migration

Revision ID: c573dc243ff9
Revises: 
Create Date: 2025-06-21 18:28:34.258731

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c573dc243ff9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_subtask',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('subtask_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.ForeignKeyConstraint(['subtask_id'], ['subtasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('student_subtasks')
    with op.batch_alter_table('milestone_upload', schema=None) as batch_op:
        batch_op.alter_column('filename',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=255),
               nullable=False)

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_constraint('student_user_id_key', type_='unique')

    with op.batch_alter_table('subtask_comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.Text(), nullable=False))
        batch_op.drop_column('comment')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subtask_comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.drop_column('content')

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.create_unique_constraint('student_user_id_key', ['user_id'])

    with op.batch_alter_table('milestone_upload', schema=None) as batch_op:
        batch_op.alter_column('filename',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=200),
               nullable=True)

    op.create_table('student_subtasks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('subtask_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('date_completed', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], name='student_subtasks_student_id_fkey'),
    sa.ForeignKeyConstraint(['subtask_id'], ['subtasks.id'], name='student_subtasks_subtask_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='student_subtasks_pkey')
    )
    op.drop_table('student_subtask')
    # ### end Alembic commands ###
