"""Add in_progress field to StudentMilestone

Revision ID: c613a50fc625
Revises: 0627c3cfac47
Create Date: 2025-06-10 20:13:06.902181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c613a50fc625'
down_revision = '0627c3cfac47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_milestones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('in_progress', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_milestones', schema=None) as batch_op:
        batch_op.drop_column('in_progress')

    # ### end Alembic commands ###
