"""empty message

Revision ID: e95f5a4ce532
Revises: c573dc243ff9
Create Date: 2025-06-23 11:23:36.876049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e95f5a4ce532'
down_revision = 'c573dc243ff9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_subtask', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_subtask', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
